# -*- coding: utf-8 -*-
"""Assignment1_Yang Yuetian.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwlM5dYlI14WOnMV-zz1n25Z_xLTdsTE
"""

# Name: [Yang Yuetian]
# Assignment One
# ddl is 22/9/2026 23:59pm

1.Simple Calculator

# 1.Additive operation
def calculator():
    print("=== Simple Calculator ===")

    # 1. Prompt for first number
    try:
        num1 = float(input("Enter first number: "))
    except ValueError:
        print("Invalid input! Please enter a valid number.")
        return

    # 2. Choose operator
    print("\nSelect an operator:")
    print(" + : Addition ")
    print(" - : Subtraction ")
    print(" * : Multiplication")
    print(" / : Division ")
    operator = input("Enter operator (+, -, *, /): ").strip()

    # 3. Prompt for second number
    try:
        num2 = float(input("Enter second number: "))
    except ValueError:
        print("Invalid input! Please enter a valid number.")
        return

    # 4. Process and display clear math result
    print("\n" + "=" * 25)
    if operator == '+':
        result = num1 + num2
        print(f"Result: {num1} + {num2} = {result}")
    elif operator == '-':
        result = num1 - num2
        print(f"Result: {num1} - {num2} = {result}")
    elif operator == '*':
        result = num1 * num2
        print(f"Result: {num1} × {num2} = {result}")
    elif operator == '/':
        if num2 == 0:
            print("Error: Division by zero is not allowed.")
        else:
            result = num1 / num2
            print(f"Result: {num1} ÷ {num2} = {result}")
    else:
        print("Invalid operator selected.")
    print("=" * 25)

if __name__ == "__main__":
    calculator()

2.QA Bot

def qa_bot():
    print("=== Welcome to the QA Bot! ===")
    print("Type your question below (or type 'exit' to quit).\n")

    while True:
        # Prompt for user input and convert it to lowercase for case-insensitive matching
        user_input = input("You: ").strip().lower()

        # Check if the user wants to exit
        if user_input == "exit":
            print("Bot: Goodbye! Have a great day!")
            break

        # Keyword 1: 'hello' or 'hi'
        if "hello" in user_input or "hi" in user_input:
            print("Bot: Hello there! How can I help you today?")

        # Keyword 2: 'python'
        elif "python" in user_input:
            print("Bot: Python is a versatile and popular high-level programming language!")

        # Keyword 3: 'jetson'
        elif "jetson" in user_input:
            print("Bot: NVIDIA Jetson is a series of embedded computing boards designed for AI at the edge.")

        # Keyword 4: 'ai'
        elif "ai" in user_input:
            print("Bot: Artificial Intelligence (AI) enables machines to simulate human intelligence and solve complex problems.")

        # Keyword 5: 'name'
        elif "name" in user_input:
            print("Bot: My name is QA Bot, your automated assistant!")

        # Default response when no keywords are matched
        else:
            print("Bot: I'm sorry, I don't understand that question yet. Try asking about 'Python', 'Jetson', 'AI', 'hello', or my 'name'.")

        print()  # Print an empty line for better readability

if __name__ == "__main__":
    qa_bot()

3. Turtle Drawing

!pip install ColabTurtle

import math
import ColabTurtle.Turtle as t


def setup_canvas():
    """Initialize canvas, set white background, and reset turtle settings."""
    t.initializeTurtle()
    t.bgcolor("white")  # Set background to white so lines are clearly visible
    t.speed(5)
    t.pensize(3)


def get_color(shape_name):
    """Validate and restrict color choices to strictly Red, Yellow, or Blue."""
    color_map = {"1": "red", "2": "yellow", "3": "blue"}
    while True:
        choice = (
            input(
                f"Select color for {shape_name} (1: Red / 2: Yellow / 3: Blue): "
            )
            .strip()
            .lower()
        )
        if choice in color_map:
            return color_map[choice]
        elif choice in ["red", "yellow", "blue"]:
            return choice
        else:
            print(
                "Invalid input! Color must strictly be Red (1), Yellow (2), or Blue (3)."
            )


# ==========================================
# 1. Draw Square (Single numeric input for side length)
# ==========================================
def draw_square():
    print("\n--- Drawing Square ---")
    while True:
        try:
            side = float(
                input(
                    "Enter side length for square (e.g., 100 or 150): "
                )
            )
            if side <= 0:
                print("Side length must be greater than 0.")
                continue
            break
        except ValueError:
            print("Invalid input! Please enter a valid number.")

    color = get_color("Square")

    setup_canvas()
    t.color(color)

    # Draw square using a for-loop
    for _ in range(4):
        t.forward(int(side))
        t.left(90)


# ==========================================
# 2. Draw Triangle (Coordinate-based for precise closing)
# ==========================================
def draw_triangle():
    print("\n--- Drawing Triangle ---")
    while True:
        try:
            a = float(input("Enter length for side a (e.g., 100): "))
            b = float(input("Enter length for side b (e.g., 100): "))
            c = float(input("Enter length for side c (e.g., 100): "))

            if a <= 0 or b <= 0 or c <= 0:
                print("All side lengths must be greater than 0!")
                continue

            # Verify triangle inequality theorem
            valid_sum = (a + b > c) and (a + c > b) and (b + c > a)
            valid_diff = (
                (abs(a - b) < c) and (abs(a - c) < b) and (abs(b - c) < a)
            )

            if valid_sum and valid_diff:
                break
            else:
                print(
                    "Invalid triangle dimensions! "
                    "Sum of any two sides must be greater than the third side, "
                    "and difference must be less than the third side."
                )
        except ValueError:
            print("Invalid input! Please enter valid numbers.")

    color = get_color("Triangle")

    # Calculate internal angle C (between side a and side b) using Law of Cosines
    cos_C = (a**2 + b**2 - c**2) / (2 * a * b)
    angle_C = math.acos(cos_C)

    setup_canvas()
    t.color(color)

    # ColabTurtle canvas default size is 800x500, set starting point
    start_x, start_y = 350, 300

    # Calculate exact 3 vertices coordinates
    # Vertex 1: Start point
    # Vertex 2: Move right along base line (side a)
    v1 = (start_x, start_y)
    v2 = (start_x + a, start_y)

    # Vertex 3: Calculated using angle C and side b
    v3 = (
        start_x + b * math.cos(angle_C),
        start_y - b * math.sin(angle_C),  # ColabTurtle Y axis points downward
    )

    # Draw closed triangle path connecting the 3 coordinates
    t.penup()
    t.goto(int(v1[0]), int(v1[1]))
    t.pendown()

    t.goto(int(v2[0]), int(v2[1]))
    t.goto(int(v3[0]), int(v3[1]))
    t.goto(int(v1[0]), int(v1[1]))  # Guaranteed exact closure2

# ==========================================
# 3. Draw Regular Star (Single numeric input for side length)
# ==========================================
def draw_star():
    print("\n--- Drawing Regular 5-Point Star ---")
    while True:
        try:
            side = float(
                input(
                    "Enter side length for star (e.g., 100 or 150): "
                )
            )
            if side <= 0:
                print("Side length must be greater than 0.")
                continue
            break
        except ValueError:
            print("Invalid input! Please enter a valid number.")

    color = get_color("Star")

    setup_canvas()
    t.color(color)

    # Regular 5-pointed star requires turning 144 degrees at each point
    for _ in range(5):
        t.forward(int(side))
        t.right(144)


# ==========================================
# Main Execution Flow
# ==========================================
def main():
    while True:
        print("\n=== Turtle Vector Graphics Program (Colab Version) ===")
        print("1. Draw Square")
        print("2. Draw Triangle")
        print("3. Draw Regular 5-Point Star")
        print("4. Exit Program")

        choice = input("Please select an option (1-4): ").strip()

        if choice == "1":
            draw_square()
        elif choice == "2":
            draw_triangle()
        elif choice == "3":
            draw_star()
        elif choice == "4":
            print("Exiting program. Goodbye!")
            break
        else:
            print("Invalid option! Please enter a number between 1 and 4.")


if __name__ == "__main__":
    main()2